name: CD compute

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:
    inputs:
      run_tests:
        type: choice
        required: false
        default: 'yes'
        description: Run tests?
        options:
          - 'yes'
          - 'no'

  workflow_call:

jobs:
  deploy-api:
    if: ${{ github.ref_name == 'prod' || github.ref_name == 'preprod' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      AWS_REGION: eu-west-3
      CODEARTIFACT_USERNAME: harena-api
      CODEARTIFACT_URL: https://maven-hei-lab-057045785189.d.codeartifact.eu-west-3.amazonaws.com/maven/patrimoine/

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - name: Disable tests
        if: ${{ github.event.inputs.run_tests == 'no' }}
        run: |
          printf "tasks.named('test').configure {\n    enabled = false\n}" >> build.gradle

      - run: |
          export CODEARTIFACT_PASSWORD=$(aws codeartifact get-authorization-token \
            --domain maven-hei-lab \
            --domain-owner 057045785189 \
            --region ${{ env.AWS_REGION }} \
            --query authorizationToken \
            --output text) &&
          sam build

      - name: Deploy application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ github.ref_name }}-compute-harena-api --capabilities CAPABILITY_IAM --parameter-overrides Env=${{ github.ref_name }} --resolve-s3 --tags app=harena-api env=${{ github.ref_name }} user:poja=harena-api

